#!/bin/bash

set -e

if [ "$1" = "configure" ] ; then
    . usr/share/shutils/kube.sh
    export -f sh_delpod
    export -f sh_pod_log
    export -f sh_pod_get
    export -f sh_pod_valid_name
    
    . usr/share/shutils/dr.sh
    export -f sh_dhubp
    export -f sh_whoisport

    . usr/share/shutils/gen.sh
    export -f sh_minfo
    export -f sh_kp
    export -f sh_psa
    export -f sh_ssd
    export -f sh_ffirst

    . usr/share/shutils/git.sh
    export -f sh_ginfo
    export -f sh_commit

    
fi
