#!/bin/bash

set -e
set -x

# loading functions
. /usr/share/shutils/shutils.sh

# export functions to bash
echo '. /usr/share/shutils/shutils.sh' > /etc/profile.d/shutils.sh

# Add shutils to bash.bashrc if not already present
if ! grep -q '/etc/profile.d/shutils.sh' /etc/bash.bashrc; then
    echo ". /etc/profile.d/shutils.sh" >> /etc/bash.bashrc
fi

# Configuração concluída
echo "Shutils install end."

# Remove shutils from bash.bashrc on package removal
if [ "$1" = "remove" ]; then
    sed -i '/\. \/etc\/profile\.d\/shutils\.sh/d' /etc/bash.bashrc
    rm -f /etc/profile.d/shutils.sh
fi