#!/bin/bash

set -e
set -x

# loading functions
. /bin/shutils/shutils.sh

# export functions to bash
echo '. /bin/shutils/shutils.sh' > /etc/profile.d/shutils.sh

# Add shutils to bash.bashrc if not already present
if ! grep -q '/etc/profile.d/shutils.sh' /etc/bash.bashrc; then
    echo ". /etc/profile.d/shutils.sh" >> /etc/bash.bashrc
fi

# Configuração concluída
echo "Shutils install end."
