#!/bin/bash

set -e
set -x

# loading functions
. /usr/share/shutils/shutils.sh

# export functions to bash
echo '. /usr/share/shutils/shutils.sh' > /etc/profile.d/shutils.sh

# Configuração concluída
echo "Shutils install end."